name: multiplier_icons
description: A new Flutter package project.
version: 1.0.0
author: Multiplier
homepage: multiplier.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_coverage_badge: ^0.0.1+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  
  assets:
    - lib/src/assets/icons/adjustments.svg
    - lib/src/assets/icons/agenda.svg
    - lib/src/assets/icons/agent.svg
    - lib/src/assets/icons/attendance.svg
    - lib/src/assets/icons/billings.svg
    - lib/src/assets/icons/budget_proposals.svg
    - lib/src/assets/icons/business_problems.svg
    - lib/src/assets/icons/catalog.svg
    - lib/src/assets/icons/change_account.svg
    - lib/src/assets/icons/clients.svg
    - lib/src/assets/icons/company.svg
    - lib/src/assets/icons/edit.svg
    - lib/src/assets/icons/exit.svg
    - lib/src/assets/icons/file_download.svg
    - lib/src/assets/icons/filter.svg
    - lib/src/assets/icons/financial.svg
    - lib/src/assets/icons/folders.svg
    - lib/src/assets/icons/historic.svg
    - lib/src/assets/icons/home.svg
    - lib/src/assets/icons/like_filled.svg
    - lib/src/assets/icons/like.svg
    - lib/src/assets/icons/localization.svg
    - lib/src/assets/icons/new_clients.svg
    - lib/src/assets/icons/orders.svg
    - lib/src/assets/icons/pallet.svg
    - lib/src/assets/icons/phone.svg
    - lib/src/assets/icons/price_table.svg
    - lib/src/assets/icons/printer.svg
    - lib/src/assets/icons/products.svg
    - lib/src/assets/icons/qr_code.svg
    - lib/src/assets/icons/recurrences.svg
    - lib/src/assets/icons/search.svg
    - lib/src/assets/icons/settings.svg
    - lib/src/assets/icons/share.svg
    - lib/src/assets/icons/star.svg
    - lib/src/assets/icons/stock.svg
    - lib/src/assets/icons/trash.svg
    - lib/src/assets/icons/truck.svg
